### ISSUE TITLE
Non-localhost IP causes wrong redirection

### ISSUE THREAD

**Issue by jakthra** [vinbigdata-medical/vindr-lab-deployment#4]
In an attempt to host it on a remote instance the authentication layer causes a wrong redirection to a localhost IP

http://remote-ip-here:8080/ will cause a redirection to

http://localhost:8080/auth/realms/vinlab/protocol/openid-connect/auth?client_id=vinlab-frontend&response_type=code&state=qi7ouyugysi&scope=profile&redirect_uri=http://localhost:8080/dashboard

What am I missing in the keycloak setup?

**Comment by iamatsundere** [comment]
Nope, I think there is nothing wrong here. Maybe I will publish the direction of the tool in the next commit.

**Comment by iamatsundere** [comment]
I've updated the Note/README in the commit [a056252](https://github.com/vinbigdata-medical/vindr-lab-deployment/commit/a0562526658652cff7bcbac4f80d4789ca077e76 ). Please check it.

**Comment by jakthra** [comment]
As I see it the redirection is done incorrectly, no? It should redirect to the base URL and not by default 'localhost'. In this case it cannot resolve localhost since the user only is able to access the remote-ip and does not have anything at his/hers 'localhost'. The redirection done by the dashboard does not resolve the correct URL to the keycloak login page in this case.

**Comment by iamatsundere** [comment]
It seems like when you do anything, It will redirect to localhost:8080, right?

**Comment by jakthra** [comment]
> It seems like when you do anything, It will redirect to localhost:8080, right?

Yeah exactly.

**Comment by iamatsundere** [comment]
Oh I got it, so sorry for this inconvenient. To change the address to your remote IP, You should find and replace all of the `localhost:8080` to `your_ip:your_port`.

**Comment by jakthra** [comment]
Ok! Makes sense. I'll create a script to make this adaptive. Thanks! Will reopen if there's further questions.
