### ISSUE TITLE
project creation problem

### ISSUE THREAD

**Issue by guigautier** [vinbigdata-medical/vindr-lab-deployment#5]
Hi, 
Firstly, many thanks for releasing this project. It's impressive.
I try to configure the project using docker-compose on ubuntu. 
I follow keycloak instructions. I got an error when I try to create a new project from the vindr frontend. 
I think I miss something, like a keycloak permission configuration. (error logs attached)
Do you have any hints ? Thank you

![image](https://user-images.githubusercontent.com/45590481/114544715-4b0c8200-9c5b-11eb-9322-c53654920f1a.png)

**Comment by iamatsundere** [comment]
Hi @guigautier, please send me your token and go to Clients/vinlab-backend, then go to tab Authorization, sub-tab Permissions and capture the UI for me.

**Comment by guigautier** [comment]
This is the url that I try to reach : http://localhost:8080/dashboard/study-list/1b8fe726-a969-47da-8152-673c754902f1?tab=setting

In console I got this 2 forbidden request  :
 http://localhost:8080/api/stats/projects_by_role?_offset=0&_limit=25&role=PROJECT_OWNER 
 http://localhost:8080/api/projects/1b8fe726-a969-47da-8152-673c754902f1

This is my Permissions UI  : 
![image](https://user-images.githubusercontent.com/45590481/114659224-7b9ffa80-9cf3-11eb-9c27-36f84dc61d37.png)

Thanks

**Comment by iamatsundere** [comment]
Sorry for the delay, please send me the token you are using.

**Comment by iamatsundere** [comment]
I've updated the installation docs, please follow this! Thanks!

**Comment by iamatsundere** [comment]
I read the reply from Gitter channel, no more comments. I will close this!
